version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 3.0.6
    commands:
      - bundle install

  pre_build:
    commands:
      - rake db:create db:migrate

  build:
    commands:
      - bundle exec rspec

# Add additional phases and commands as needed for your specific requirements
