version: "3.8"
services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      RAILS_ENV: production
    command: ["rails", "server", "-e", "production", "-b", "0.0.0.0"]